using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;

namespace KsWare.Presentation.ViewFramework.Resources {

	/// <summary>
	/// Provides the KsWare.Presentation.ViewFramework/Resources/ViewModelStyles.xaml as <see cref="ResourceDictionary"/>
	/// </summary>
	/// <seealso cref="KsWare.Presentation.ViewFramework.SharedResourceDictionary" />
	/// <seealso cref="ResourceDictionary" />
	partial class ViewModelStylesResources {

		/// <summary>
		/// Initializes a new instance of the <see cref="ViewModelStylesResources"/> class.
		/// </summary>
		/// <autogeneratedoc />
		public ViewModelStylesResources() {
			InitializeComponent();
			Source = new Uri("pack://application:,,,/KsWare.Presentation.ViewFramework;component/Resources/ViewModelStyles.xaml",UriKind.Absolute);
		}
	}
}
