using System;
using System.Collections.Generic;
using KsWare.Presentation.BusinessFramework;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace KsWare.Presentation.Tests.BusinessFramework {

    /// <summary>
    /// Test Class
    /// </summary>
    [TestClass]
    public class BusinessList_2_Tests {
        /// <summary> Setup this instance.
        /// </summary>
        [TestInitialize]
        public void Setup()
        {

        }

        /// <summary> Teardowns this instance.
        /// </summary>
        [TestCleanup]
        public void Teardown()
        {

        }
        /// <summary>
        /// Test the function
        /// </summary>
        [TestMethod]
        public void BusinessList_Value_LocalDataProvider()
        {
        	var list = new ListBM<StringBM>();
        	list.Metadata.DataProvider.Data = new List<string>(new [] {"A", "B", "C"});
			list.Add(new StringBM{Metadata = {DataProvider={Data = "D"}}});
			list.RemoveAt(0);
        }

		/// <summary>
        /// Test the function
        /// </summary>
        [TestMethod]
        public void BusinessList_Enum_LocalDataProvider()
        {
        	var list = new ListBM<EnumBM<TestEnum>>();
        	list.Metadata.DataProvider.Data = new List<TestEnum>(new [] {TestEnum.A, TestEnum.B, TestEnum.C});
			list.Add(new EnumBM<TestEnum>{Metadata = {DataProvider={Data= TestEnum.C}}});
			list.RemoveAt(0);
        }

		/// <summary>
        /// Test the function
        /// </summary>
        [TestMethod]
        public void BusinessList_Object_LocalDataProvider()
        {
        	var list = new ListBM<TestObject>();
        	list.Metadata.DataProvider.Data = new List<TestData>(new [] {new TestData{A=1,B="1",C=DateTime.Now},new TestData{A=2,B="2",C=DateTime.Now}});
			list.Add(new TestObject{Metadata = {DataProvider={Data= new TestData{A=3,B="3",C=DateTime.Now}}}});
			list.RemoveAt(0);
        }

		public enum TestEnum {
			A,B,C
		}

		public class TestData {
			public int A { get; set; }
    		public string B{get;set;}
			public DateTime C{get;set;}
		}

		public class TestObject:ObjectBM {
			public TestObject() {
				//Metadata=AutoGenerated;
			}
		}
    }
}
