using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Windows;

namespace KsWare.Presentation.ViewFramework {

	/// <summary>
	/// Provides a <see cref="ResourceDictionary"/> which is used only at design time.
	/// </summary>
	/// <seealso cref="System.Windows.ResourceDictionary" />
	/// <autogeneratedoc />
	public class DesigntimeResourceDictionary : ResourceDictionary {

		private static readonly bool IsInDesignMode = DesignerProperties.GetIsInDesignMode(new DependencyObject());

		/// <inheritdoc cref="ResourceDictionary.Source"/>
		/// <remarks>Source is allways null at runtime.</remarks>
		public new Uri Source {
			get => IsInDesignMode ? base.Source : null;
			set => base.Source = IsInDesignMode ? value : null;
		}

	}
}