namespace KsWare.Presentation.ViewModelFramework {

	/// <summary>
	/// Class UIElementVM.
	/// </summary>
	/// <typeparam name="T"></typeparam>
	/// <seealso cref="KsWare.Presentation.ViewModelFramework.ObjectVM" />
	/// <autogeneratedoc />
	public class UIElementVM<T> : ObjectVM {

		public UIElementVM() {
			RegisterChildren(()=>this);
		}
	}

}