using System.Windows;

namespace KsWare.Presentation.ViewModelFramework {

	/// <summary>
	/// Class UIElementControllerVM.
	/// </summary>
	/// <typeparam name="T">Type of UIElement</typeparam>
	public class UIElementControllerVM<T> : UIElementVM<T>, IUIElementControllerVM where T : UIElement {

		/// <summary>
		/// Initializes a new instance of the <see cref="UIElementControllerVM{T}"/> class.
		/// </summary>
		/// <autogeneratedoc />
		public UIElementControllerVM() {
			RegisterChildren(() => this);
		}

		/// <summary>
		/// Gets the UI element.
		/// </summary>
		/// <value>The UI element.</value>
		/// <autogeneratedoc />
		protected T UIElement { get; private set; }

		void IUIElementControllerVM.Connect(UIElement uiElement) {
			UIElement = (T) uiElement;
			OnConnected();
		}

		protected virtual void OnConnected() { }
	}

	public interface IUIElementControllerVM {

		void Connect(UIElement uiElement);
	}

}